version: '3.8'

services: 
    my_airflow:
        build: ./poneglyph/airflow/setup/airflow
        image: my_airflow_image
        ports: 
            - target: 8080
              published: 8080
        container_name: my_airflow_container
        volumes:
            - ./poneglyph/airflow/dags:/usr/local/airflow/dags
            - ./poneglyph/airflow/plugins:/usr/local/airflow/plugins


    my_sql:
        image: mysql:latest
        container_name: mysql_container
        ports: 
            - 3307:3306
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        volumes:
            - ./poneglyph/airflow/setup/sql:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql


volumes: 
    mysql_data:


